import os
from constant import DATABASE_URI, SQLALCHEMY_TRACK_MODIFICATIONS


class Config:
    SQLALCHEMY_DATABASE_URI = DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = SQLALCHEMY_TRACK_MODIFICATIONS
